// <auto-generated />
using System;
using HotelPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelPlatform.Domain.Files.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("stored_files", (string)null);
                });

            modelBuilder.Entity("HotelPlatform.Domain.Hotels.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<Guid?>("hotel_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("hotel_id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("HotelPlatform.Domain.Hotels.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("Hotels", (string)null);
                });

            modelBuilder.Entity("HotelPlatform.Domain.Ratings.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.HasIndex("HotelId", "UserId")
                        .IsUnique();

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("HotelPlatform.Domain.ReferenceData.HotelAmenityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemDefined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("hotel_amenity_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "Recreation",
                            Code = "POOL",
                            Icon = "pool",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "Recreation",
                            Code = "GYM",
                            Icon = "gym",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Fitness Center"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "Recreation",
                            Code = "SPA",
                            Icon = "spa",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Spa & Wellness"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "Services",
                            Code = "RESTAURANT",
                            Icon = "restaurant",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "Services",
                            Code = "BAR",
                            Icon = "bar",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Bar & Lounge"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "Services",
                            Code = "ROOM_SERVICE",
                            Icon = "room-service",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Room Service"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Category = "Services",
                            Code = "CONCIERGE",
                            Icon = "concierge",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Concierge Service"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Category = "Services",
                            Code = "LAUNDRY",
                            Icon = "laundry",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Laundry Service"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Category = "Facilities",
                            Code = "PARKING",
                            Icon = "parking",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Parking"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            Category = "Facilities",
                            Code = "WIFI",
                            Icon = "wifi",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Free WiFi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            Category = "Facilities",
                            Code = "BUSINESS_CENTER",
                            Icon = "business",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Business Center"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            Category = "Facilities",
                            Code = "MEETING_ROOMS",
                            Icon = "meeting",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Meeting Rooms"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            Category = "Accessibility",
                            Code = "WHEELCHAIR",
                            Icon = "wheelchair",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Wheelchair Accessible"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            Category = "Accessibility",
                            Code = "ELEVATOR",
                            Icon = "elevator",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Elevator"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            Category = "Family",
                            Code = "KIDS_CLUB",
                            Icon = "kids",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Kids Club"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Category = "Family",
                            Code = "BABYSITTING",
                            Icon = "babysitting",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Babysitting Service"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Category = "Pets",
                            Code = "PET_FRIENDLY",
                            Icon = "pet",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Pet Friendly"
                        });
                });

            modelBuilder.Entity("HotelPlatform.Domain.ReferenceData.RoomAmenityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemDefined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("room_amenity_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Category = "Comfort",
                            Code = "AC",
                            Icon = "ac",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Category = "Comfort",
                            Code = "HEATING",
                            Icon = "heating",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Heating"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Category = "Comfort",
                            Code = "BALCONY",
                            Icon = "balcony",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Balcony"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Category = "Comfort",
                            Code = "SEA_VIEW",
                            Icon = "sea-view",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Sea View"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Category = "Comfort",
                            Code = "CITY_VIEW",
                            Icon = "city-view",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "City View"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Category = "Entertainment",
                            Code = "TV",
                            Icon = "tv",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Flat Screen TV"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Category = "Entertainment",
                            Code = "STREAMING",
                            Icon = "streaming",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Streaming Services"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Category = "Entertainment",
                            Code = "ROOM_WIFI",
                            Icon = "wifi",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "In-Room WiFi"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Category = "Refreshments",
                            Code = "MINIBAR",
                            Icon = "minibar",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Mini Bar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000a"),
                            Category = "Refreshments",
                            Code = "COFFEE_MAKER",
                            Icon = "coffee",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000b"),
                            Category = "Refreshments",
                            Code = "KETTLE",
                            Icon = "kettle",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Electric Kettle"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000c"),
                            Category = "Bathroom",
                            Code = "BATHTUB",
                            Icon = "bathtub",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Bathtub"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000d"),
                            Category = "Bathroom",
                            Code = "RAIN_SHOWER",
                            Icon = "shower",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Rain Shower"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000e"),
                            Category = "Bathroom",
                            Code = "TOILETRIES",
                            Icon = "toiletries",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Premium Toiletries"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000f"),
                            Category = "Bathroom",
                            Code = "HAIR_DRYER",
                            Icon = "hairdryer",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Category = "Work",
                            Code = "WORK_DESK",
                            Icon = "desk",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Work Desk"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Category = "Safety",
                            Code = "SAFE",
                            Icon = "safe",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "In-Room Safe"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Category = "Sleep",
                            Code = "KING_BED",
                            Icon = "bed",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "King Size Bed"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Category = "Sleep",
                            Code = "TWIN_BEDS",
                            Icon = "beds",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Twin Beds"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Category = "Sleep",
                            Code = "BLACKOUT_CURTAINS",
                            Icon = "curtains",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Blackout Curtains"
                        });
                });

            modelBuilder.Entity("HotelPlatform.Domain.ReferenceData.RoomTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("default_capacity");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemDefined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("room_type_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "SINGLE",
                            DefaultCapacity = 1,
                            Description = "Cozy room for one guest with a single bed",
                            Icon = "single-room",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Single Room"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "DOUBLE",
                            DefaultCapacity = 2,
                            Description = "Comfortable room with a double bed for two guests",
                            Icon = "double-room",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Double Room"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "TWIN",
                            DefaultCapacity = 2,
                            Description = "Room with two single beds",
                            Icon = "twin-room",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Twin Room"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Code = "TRIPLE",
                            DefaultCapacity = 3,
                            Description = "Spacious room accommodating three guests",
                            Icon = "triple-room",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Triple Room"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Code = "QUAD",
                            DefaultCapacity = 4,
                            Description = "Large room for four guests",
                            Icon = "quad-room",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Quad Room"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Code = "SUITE",
                            DefaultCapacity = 2,
                            Description = "Luxurious suite with separate living area",
                            Icon = "suite",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Suite"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Code = "JUNIOR_SUITE",
                            DefaultCapacity = 2,
                            Description = "Elegant suite with combined sleeping and sitting area",
                            Icon = "junior-suite",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Junior Suite"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Code = "PRESIDENTIAL_SUITE",
                            DefaultCapacity = 4,
                            Description = "Ultimate luxury with multiple rooms and premium amenities",
                            Icon = "presidential-suite",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Presidential Suite"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Code = "FAMILY",
                            DefaultCapacity = 4,
                            Description = "Spacious room designed for families with children",
                            Icon = "family-room",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Family Room"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000a"),
                            Code = "DELUXE",
                            DefaultCapacity = 2,
                            Description = "Premium room with enhanced amenities and extra space",
                            Icon = "deluxe-room",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Deluxe Room"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000b"),
                            Code = "STUDIO",
                            DefaultCapacity = 2,
                            Description = "Self-contained room with kitchenette",
                            Icon = "studio",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Studio"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000c"),
                            Code = "PENTHOUSE",
                            DefaultCapacity = 4,
                            Description = "Top-floor luxury accommodation with panoramic views",
                            Icon = "penthouse",
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Penthouse"
                        });
                });

            modelBuilder.Entity("HotelPlatform.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HotelPlatform.Domain.Hotels.Entities.Room", b =>
                {
                    b.HasOne("HotelPlatform.Domain.Hotels.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("hotel_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("HotelPlatform.Domain.Common.ValueObjects.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("base_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("base_price_currency");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("HotelPlatform.Domain.Common.ValueObjects.RoomPicture", "Pictures", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("AltText")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("alt_text");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<bool>("IsMain")
                                .HasColumnType("boolean")
                                .HasColumnName("is_main");

                            b1.Property<Guid>("StoredFileId")
                                .HasColumnType("uuid")
                                .HasColumnName("stored_file_id");

                            b1.Property<Guid>("room_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("room_id", "StoredFileId")
                                .IsUnique();

                            b1.ToTable("room_pictures", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("room_id");
                        });

                    b.OwnsMany("HotelPlatform.Domain.Common.ValueObjects.RoomSelectedAmenity", "Amenities", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<Guid>("AmenityDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("amenity_definition_id");

                            b1.Property<Guid>("room_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("room_id", "AmenityDefinitionId")
                                .IsUnique();

                            b1.ToTable("room_selected_amenities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("room_id");

                            b1.OwnsOne("HotelPlatform.Domain.Common.ValueObjects.Upcharge", "Upcharge", b2 =>
                                {
                                    b2.Property<int>("RoomSelectedAmenityid")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("upcharge_amount");

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("upcharge_currency");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasColumnName("upcharge_type");

                                    b2.HasKey("RoomSelectedAmenityid");

                                    b2.ToTable("room_selected_amenities");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomSelectedAmenityid");
                                });

                            b1.Navigation("Upcharge")
                                .IsRequired();
                        });

                    b.Navigation("Amenities");

                    b.Navigation("BasePrice")
                        .IsRequired();

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("HotelPlatform.Domain.Hotels.Hotel", b =>
                {
                    b.OwnsOne("HotelPlatform.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("address_street");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");

                            b1.OwnsOne("HotelPlatform.Domain.Common.ValueObjects.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("AddressHotelId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_longitude");

                                    b2.HasKey("AddressHotelId");

                                    b2.ToTable("Hotels");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressHotelId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsOne("HotelPlatform.Domain.Common.ValueObjects.AggregatedRating", "AggregatedRating", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AverageScore")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(3, 2)
                                .HasColumnType("numeric(3,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("rating_average");

                            b1.Property<int>("TotalCounts")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("rating_total_counts");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsMany("HotelPlatform.Domain.Common.ValueObjects.HotelPicture", "Pictures", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("AltText")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("alt_text");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<bool>("IsMain")
                                .HasColumnType("boolean")
                                .HasColumnName("is_main");

                            b1.Property<Guid>("StoredFileId")
                                .HasColumnType("uuid")
                                .HasColumnName("stored_file_id");

                            b1.Property<Guid>("hotel_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("hotel_id", "StoredFileId")
                                .IsUnique();

                            b1.ToTable("hotel_pictures", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("hotel_id");
                        });

                    b.OwnsMany("HotelPlatform.Domain.Common.ValueObjects.HotelSelectedAmenity", "Amenities", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<Guid>("AmenityDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("amenity_definition_id");

                            b1.Property<Guid>("hotel_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("hotel_id", "AmenityDefinitionId")
                                .IsUnique();

                            b1.ToTable("hotel_selected_amenities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("hotel_id");

                            b1.OwnsOne("HotelPlatform.Domain.Common.ValueObjects.Upcharge", "Upcharge", b2 =>
                                {
                                    b2.Property<int>("HotelSelectedAmenityid")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("upcharge_amount");

                                    b2.Property<string>("Currency")
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("upcharge_currency");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasColumnName("upcharge_type");

                                    b2.HasKey("HotelSelectedAmenityid");

                                    b2.ToTable("hotel_selected_amenities");

                                    b2.WithOwner()
                                        .HasForeignKey("HotelSelectedAmenityid");
                                });

                            b1.Navigation("Upcharge")
                                .IsRequired();
                        });

                    b.Navigation("Address");

                    b.Navigation("AggregatedRating")
                        .IsRequired();

                    b.Navigation("Amenities");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("HotelPlatform.Domain.Hotels.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
